### PR TITLE
Set testem port

### PR DESCRIPTION
**Pull request by asakusuma**

### CODE REVIEW

**Comment by rwjblue** [comment]
I believe that setting to 0 is supposed to pick a random port.

**Comment by asakusuma** [comment]
That doesn't happen locally for me:

```
TEST'EM 'SCRIPTS!                                                                                                                                                                                         
Open the URL below in a browser to connect.                                                                                                                                                               
http://localhost:0/ 
```

**Comment by dgeb** [comment]
@asakusuma what version of testem do you have installed globally? `testem --version`

**Comment by robbiepitts** [comment]
@asakusuma Also, what was the command you used to run it? I'm able to reproduce with `testem -s`. I stumbled upon this by accident because I'm used to doing `ember t -s ...`. The `-s` option for testem is a totally different thing I found out.

**Comment by asakusuma** [comment]
@dgeb I was on `1.6.0`. Upgrading fixed it.

@robbiepitts FWIW, I was running `testem`

Thanks guys, closing

**Pull request closed without merging**
